# Generated by Django 2.0.4 on 2018-04-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoobject',
            name='EngineCapacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='AMru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.AMruObject', verbose_name='Дром'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='Avito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.AvitoObject', verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='Drom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.DromObject', verbose_name='Дром'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='EngineCapacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='Youla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.YoulaObject', verbose_name='Дром'),
        ),
    ]
