# Generated by Django 2.0.4 on 2018-04-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0005_auto_20180405_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amruobject',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ColorOfAuto', verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='amruobject',
            name='MarkAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MarkOfAuto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='amruobject',
            name='ModelAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ModelOfAuto', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='BodyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.BodyTypeOfAuto', verbose_name='Тип кузова автомобиля'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ColorOfAuto', verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='DriveUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.DriveUnitOfAuto', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='MarkAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MarkOfAuto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='ModelAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ModelOfAuto', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='avitoobject',
            name='TransmissionType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.TransmissionTypeOfAuto', verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MainAdObject', verbose_name='Комментируемое Объявление'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dromobject',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ColorOfAuto', verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='dromobject',
            name='MarkAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MarkOfAuto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='dromobject',
            name='ModelAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ModelOfAuto', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='BodyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.BodyTypeOfAuto', verbose_name='Тип кузова автомобиля'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ColorOfAuto', verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='DriveUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.DriveUnitOfAuto', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='MarkAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MarkOfAuto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='ModelAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ModelOfAuto', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='mainadobject',
            name='TransmissionType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.TransmissionTypeOfAuto', verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='youlaobject',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ColorOfAuto', verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='youlaobject',
            name='MarkAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.MarkOfAuto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='youlaobject',
            name='ModelAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregation.ModelOfAuto', verbose_name='Модель автомобиля'),
        ),
    ]
